### PR TITLE
LVGL v9.1

### PR DESCRIPTION
**Pull request by rzeldent**

### CODE REVIEW

**Comment by xperiments** [comment]
YES!!!!

Thanks a lot for the hard work

**Comment by rzeldent** [comment]
Hi Rene, 

I already noticed this. Looks like SPI ram is not used,
Momory allocation has changed in LVGL9 and looking into this issue.

**Comment by rzeldent** [comment]
Seems to run at 30fps (esp32-8048s070c).
However still some problems for rotation...

**Comment by rzeldent** [comment]
Rotation has been solved! Was issue in LVGL library...

**Pull request merged**
